version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_LOCAL_WHISPER_API: ${USE_LOCAL_WHISPER_API}
    container_name: payretailers_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - GPT4O_MINI_DEPLOYMENT=${GPT4O_MINI_DEPLOYMENT}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - USE_LOCAL_WHISPER_API=${USE_LOCAL_WHISPER_API}
      - GROQ_API_KEY=${GROQ_API_KEY}
    env_file:
      - .env
